default: &default
  adapter: postgresql
  encoding: unicode
  username: 'nate'
  password: ''
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: heimdallr_development

test:
  <<: *default
  database: heimdallr_test

production:
  <<: *default
  database: heimdallr_production
